---
title: "R Notebook"
output: 
  html_notebook: 
    fig_caption: yes
    number_sections: yes
    toc: yes
---

研究股票的因素模型


```{r setup, include=FALSE  }

library(tidyverse)
library(lubridate)
library(stringr)
library(shiny)
library(zstmodelr)

# Set global options for knitr 
knitr::opts_chunk$set(
comment = "#>",
echo = FALSE,
warning = FALSE,
message = FALSE,
collapse = TRUE
)

options(tibble.print_min = 10L, tibble.print_max = 20L)

```

# Data Preparation(数据准备)
```{r set_params_study}
# Set params of study

table_indicator <- "FR_T5_盈利能力"

# Set stocks as portfolio
stock_stkcds_list <- c(600066,000550, 600031, 000157,000651, 000333)

fundamental_factors_list <- c("GPM", "ROCE", "PE", "PB", "CUR", "QR")


```


## Set Params of Study(设置研究参数)


## Load facotrs data (加载因子数据)
```{r load_factors_data}
# Open gta stock databse
stock_db <- stock_db(gta_db, "GTA_SQLData")
open_stock_db(stock_db)

# Initate the stock database
invisible(init_stock_db(stock_db))
stock_name_list  <- stock_name_list(stock_db)
stock_field_list <- stock_field_list(stock_db)

# Get fundamental_facotrs
fundamental_factors <- get_factor_indicator(stock_db, 
                                factor_list = fundamental_factors_list)

fundamental_factors.zscore <- fundamental_factors %>%
  mutate_at(fundamental_factors_list, scale)


```

